[build]
  publish = "public"
  command = "npm run build"
  [[plugins]]
  package = "netlify-plugin-image-optim"
  [[plugins]]
  package = "netlify-plugin-gatsby-cache"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
